language: node_js
node_js:
  - '12'
install:
  - npm install
jobs:
  include:
    - stage: test
      script:
        - npm run unit
    - stage: GitHubPages
      script:
        - npm run docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GET_REPO_TOKEN
        keep_history: true
        local_dir: ./docs/.vuepress/dist
        fqdn: trump.chensenran.top
        on:
          branch: master
    - stage: npm release
      if: tag IS present
      node_js: "12"
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        tag: next
        on:
          tags: true
